#!/usr/bin/env bash

export CONTECO_LABEL="package.registry - ModEco"
export CONTECO_DESCRIPTION="The registry module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="registry"
export CONTECO_TAG="2"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
