#!/usr/bin/env bash

export CONTECO_LABEL="package.registry - ModEco"
export CONTECO_DESCRIPTION="The registry module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="registry"
export CONTECO_TAG="v1.0.0"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
