#!/usr/bin/env bash


prefix="package_$2"


executionplane --silent docker container prune --force

if [[ "package_registry_registry_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume rm --force package_registry_registry_volume
	fi
	
