---
version: '3'
services:

# START SERVICE registry.base
  registry:
    image: ${CONTECO_REGISTRY}${CONTECO_REALM_RUNTIME}/conteco.registry.base:2
    environment: []
    command: []
    volumes: [package_registry_registry_volume:/var/lib/registry]
    ports: [${REGISTRY_PORTS}]
    networks: [package_overlay]
    deploy:
      mode: replicated
      ${REGISTRY_DEPLOY_MODE_REPLICATED_REPLICAS}
      resources:
        limits:
          cpus: '${REGISTRY_DEPLOY_RESOURCES_LIMITS_CPUS}'
          memory: '${REGISTRY_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          cpus: '${REGISTRY_DEPLOY_RESOURCES_RESERVATIONS_CPUS}'
          memory: '${REGISTRY_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
      placement:
        constraints: [${REGISTRY_DEPLOY_PLACEMENT_CONSTRAINTS}]
      labels: [${REGISTRY_DEPLOY_LABELS}]
    labels: [${REGISTRY_LABELS}]
# END SERVICE registry.base

volumes: {package_registry_registry_volume: { external: true }}
networks: {package_overlay: { external: true }}
